name: fitmirror_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  equatable: ^2.0.5
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  go_router: ^16.0.0
  flutter_riverpod: ^2.5.4
  riverpod_annotation: ^2.3.5 # <-- ¡Esta es clave y debe estar aquí!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.5.4 # La versión compatible que encontramos
  custom_lint: ^0.7.6
  riverpod_generator: ^2.6.5 # La versión compatible
  source_gen: ^2.0.0 # La versión compatible
  analyzer: ^7.0.0 # La versión compatible