// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEM5mn2GtO3sv-MxAjYG58O949ShMgGPk',
    appId: '1:789265813244:android:d16a3a36381eb3fe80d179',
    messagingSenderId: '789265813244',
    projectId: 'fit-mirror-a-i-nwusib',
    storageBucket: 'fit-mirror-a-i-nwusib.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhX81oUGSfpooQwJxtckLE-XwNgF_oy9I',
    appId: '1:789265813244:ios:a9fe78c7f154ed2680d179',
    messagingSenderId: '789265813244',
    projectId: 'fit-mirror-a-i-nwusib',
    storageBucket: 'fit-mirror-a-i-nwusib.firebasestorage.app',
    androidClientId:
        '789265813244-h41lfiq3tmvdl2jht4s86ap1lr20c7rs.apps.googleusercontent.com',
    iosClientId:
        '789265813244-qi702vth61ii8eovh1e22dlmd61e03kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitmirrorAi',
  );
}
